"""Stakeholder reporting: merge local drafts with live GitHub state and export Excel.

The planning metadata lives in ``docs/draft_tasks/*.md``; what actually happened
lives on GitHub. This module merges the two into a single workbook so
stakeholders (course staff, team, business role) can see the epic-level picture
without touching GitHub:

- **Overview**  - summary metrics, one row per epic (Gate), one row per Stream
- **Changelog** - what changed since the previous export (snapshot diff)
- **Tasks**     - every draft task with merged state
- **Questions** - every open ``## Questions to Resolve`` item from the drafts

The workbook is generated by ``report export``; nothing is written back to
GitHub, so a report can be produced at any moment.
"""

import json
import re
from datetime import date
from pathlib import Path

from .planner import (
    GATE_ORDER,
    GATE_TAG_TO_NAME,
    load_tasks,
    resolve_issue_stamps,
    task_issue_stamp,
)

STREAM_TAG_TO_NAME = {
    "stream:a-identity": "A-Identity",
    "stream:b-patient": "B-Patient",
    "stream:c-notes": "C-Notes",
    "stream:d-audit": "D-Audit",
}
STREAM_ORDER = ["A-Identity", "B-Patient", "C-Notes", "D-Audit"]

STATE_PLANNED = "Planned"  # draft only, no GitHub card yet
STATE_OPEN = "Open"
STATE_CLOSED = "Closed"

_QUESTION_SECTION = re.compile(
    r"^## Questions to Resolve[ \t]*\n(?P<body>.*?)(?=^## |\Z)", re.MULTILINE | re.DOTALL
)
_QUESTION_BULLET = re.compile(r"^-\s*(?:\[(?P<mark>[ xX])\]\s*)?(?P<text>.+)$")


def task_gate(task):
    """Return the gate name for a task from its tags ('' when untagged)."""
    return next(
        (
            GATE_TAG_TO_NAME[tag.lower().strip()]
            for tag in task.tags
            if tag.lower().strip() in GATE_TAG_TO_NAME
        ),
        "",
    )


def task_stream(task):
    """Return the stream name for a task from its tags ('' when untagged)."""
    return next(
        (
            STREAM_TAG_TO_NAME[tag.lower().strip()]
            for tag in task.tags
            if tag.lower().strip() in STREAM_TAG_TO_NAME
        ),
        "",
    )


def parse_questions(path):
    """Parse the ``## Questions to Resolve`` checklist of a draft file.

    Returns a list of ``{"question": str, "resolved": bool}``. Plain bullets
    count as unresolved.
    """
    text = Path(path).read_text(encoding="utf-8")
    section = _QUESTION_SECTION.search(text)
    if not section:
        return []
    questions = []
    for line in section.group("body").splitlines():
        match = _QUESTION_BULLET.match(line.strip())
        if not match:
            continue
        questions.append(
            {
                "question": match.group("text").strip(),
                "resolved": bool(match.group("mark") and match.group("mark").lower() == "x"),
            }
        )
    return questions


def _ref_text(value, draft_path):
    """Render Dependencies/Related metadata as readable issue/key text."""
    numbers, unresolved = resolve_issue_stamps(draft_path, value)
    parts = [f"#{number}" for number in numbers]
    parts.extend(name.split("-", 1)[0] for name in unresolved)
    return ", ".join(parts)


def collect_rows(directory, github=None, today=None):
    """Merge draft tasks with GitHub issue state into report rows.

    ``github`` maps issue numbers to ``{"state": "open"|"closed", "url": str}``.
    Pass ``{}`` when GitHub is unreachable: stamped tasks are then reported as
    Open (assumed live) and a warning flag is set.
    """
    github = github or {}
    today = today or date.today()
    rows = []
    for task in load_tasks(directory):
        number = task_issue_stamp(task.path)
        gh = github.get(number) if number else None
        if number is None:
            state = STATE_PLANNED
            github_url = ""
        elif gh is not None:
            state = STATE_CLOSED if gh.get("state") == "closed" else STATE_OPEN
            github_url = gh.get("url", "")
        else:
            state = STATE_OPEN  # card exists but no live data (offline export)
            github_url = ""
        deadline = task.deadline.isoformat() if task.deadline else ""
        blocked = bool(_ref_text(task.dependencies, task.path)) and state == STATE_OPEN
        rows.append(
            {
                "key": task.key,
                "title": task.title,
                "gate": task_gate(task) or "Other",
                "stream": task_stream(task) or "",
                "assignee": task.assignee,
                "deadline": deadline,
                "effort": task.effort,
                "state": state,
                "github_number": number or "",
                "github_url": github_url,
                "blocked_by": _ref_text(task.dependencies, task.path),
                "related": _ref_text(", ".join(task.related), task.path),
                "blocked": blocked,
                "overdue": bool(
                    deadline and deadline < today.isoformat() and state != STATE_CLOSED
                ),
                "unassigned": task.assignee.upper() in {"TBD", "TEAM"} or not task.assignee,
                "questions": parse_questions(task.path),
            }
        )
    return rows


def _group_summary(rows):
    total = len(rows)
    planned = sum(1 for row in rows if row["state"] == STATE_PLANNED)
    open_count = sum(1 for row in rows if row["state"] == STATE_OPEN)
    closed = sum(1 for row in rows if row["state"] == STATE_CLOSED)
    deadlines = [
        row["deadline"] for row in rows if row["deadline"] and row["state"] != STATE_CLOSED
    ]
    return {
        "tasks": total,
        "planned": planned,
        "open": open_count,
        "closed": closed,
        "blocked": sum(1 for row in rows if row["blocked"]),
        "overdue": sum(1 for row in rows if row["overdue"]),
        "unassigned": sum(1 for row in rows if row["unassigned"]),
        "next_deadline": min(deadlines) if deadlines else "",
    }


def group_by(rows, key, order):
    """Group rows by ``key`` keeping ``order`` first, extras after."""
    grouped = {name: [] for name in order}
    extras = []
    for row in rows:
        value = row[key]
        if value in grouped:
            grouped[value].append(row)
        else:
            extras.append(row)
    if extras:
        grouped["Other"] = extras
    return grouped


def build_report(directory, github=None, today=None):
    """Build the full report structure used by both JSON mode and Excel export."""
    rows = collect_rows(directory, github, today)
    grouped = group_by(rows, "gate", GATE_ORDER)
    gates = [{"name": name, **(_group_summary(grouped[name]))} for name in grouped]
    grouped_streams = group_by(rows, "stream", STREAM_ORDER)
    streams = [
        {"name": name or "Unassigned", **(_group_summary(grouped_streams[name]))}
        for name in grouped_streams
    ]
    questions = [
        {
            "key": row["key"],
            "title": row["title"],
            "gate": row["gate"],
            "question": item["question"],
            "resolved": item["resolved"],
        }
        for row in rows
        for item in row["questions"]
    ]
    return {
        "rows": rows,
        "gates": gates,
        "streams": streams,
        "questions": questions,
        "summary": _group_summary(rows),
    }


# ── Snapshot & changelog ─────────────────────────────────────────────────────

_SNAPSHOT_FIELDS = (
    "title",
    "gate",
    "stream",
    "state",
    "assignee",
    "deadline",
    "effort",
    "blocked_by",
    "related",
    "github_number",
)

_FIELD_LABELS = {
    "title": "Title",
    "gate": "Epic (Gate)",
    "stream": "Stream",
    "state": "State",
    "assignee": "Assignee",
    "deadline": "Deadline",
    "effort": "Effort",
    "blocked_by": "Blocked by",
    "related": "Related",
    "github_number": "GitHub card",
}


def snapshot_for_report(report, generated_at="", repository=""):
    """Reduce a report to the minimal per-task state used for diffing."""
    tasks = {}
    for row in report["rows"]:
        item = {field: row[field] for field in _SNAPSHOT_FIELDS}
        item["questions"] = row["questions"]
        tasks[row["key"]] = item
    return {"generated_at": generated_at, "repository": repository, "tasks": tasks}


def save_snapshot(path, snapshot):
    """Write the snapshot JSON next to the exported workbook."""
    Path(path).write_text(json.dumps(snapshot, indent=2, ensure_ascii=False), encoding="utf-8")


def load_snapshot(path):
    """Read a previous snapshot, or None when missing/corrupt."""
    snapshot_path = Path(path)
    if not snapshot_path.exists():
        return None
    try:
        return json.loads(snapshot_path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None


def _text(value):
    """Render a snapshot value for display ('' for empty/None)."""
    if value in (None, ""):
        return ""
    if isinstance(value, int):
        return f"#{value}"
    return str(value)


def _question_entries(key, title, old_items, new_items):
    """Changelog entries for question additions/removals/resolution flips."""
    old_map = {item["question"]: item["resolved"] for item in old_items}
    new_map = {item["question"]: item["resolved"] for item in new_items}
    entries = []
    for question in sorted(set(new_map) - set(old_map)):
        entries.append(
            {
                "sheet": "Questions",
                "task": f"{key} {title}",
                "change": "Question added",
                "before": "",
                "after": question,
            }
        )
    for question in sorted(set(old_map) - set(new_map)):
        entries.append(
            {
                "sheet": "Questions",
                "task": f"{key} {title}",
                "change": "Question removed",
                "before": question,
                "after": "",
            }
        )
    for question in sorted(set(old_map) & set(new_map)):
        if old_map[question] == new_map[question]:
            continue
        now_resolved = new_map[question]
        entries.append(
            {
                "sheet": "Questions",
                "task": f"{key} {title}",
                "change": "Resolved" if now_resolved else "Reopened",
                "before": "Yes" if old_map[question] else "No",
                "after": "Yes" if now_resolved else "No",
            }
        )
    return entries


def diff_reports(previous, current):
    """Changelog entries between a previous snapshot and the current report.

    Returns a list of ``{"sheet", "task", "change", "before", "after"}`` rows.
    Returns ``[]`` when there is no previous snapshot to compare against.
    """
    if not previous:
        return []
    previous_tasks = previous.get("tasks", {})
    current_tasks = {row["key"]: row for row in current["rows"]}
    entries = []
    for key in sorted(set(previous_tasks) | set(current_tasks)):
        old = previous_tasks.get(key)
        new = current_tasks.get(key)
        if old is None:
            entries.append(
                {
                    "sheet": "Tasks",
                    "task": f"{new['key']} {new['title']}",
                    "change": "New task added",
                    "before": "",
                    "after": new["title"],
                }
            )
            continue
        if new is None:
            entries.append(
                {
                    "sheet": "Tasks",
                    "task": f"{key} {old['title']}",
                    "change": "Task removed",
                    "before": old["title"],
                    "after": "",
                }
            )
            continue
        title = new["title"]
        for field in _SNAPSHOT_FIELDS:
            before = _text(old.get(field))
            after = _text(new.get(field))
            if before == after:
                continue
            # A card that was never on GitHub becoming stamped is its own story.
            if field == "github_number" and before:
                continue
            entries.append(
                {
                    "sheet": "Tasks",
                    "task": f"{key} {title}",
                    "change": _FIELD_LABELS[field],
                    "before": before,
                    "after": after,
                }
            )
        old_questions = old.get("questions", []) or []
        new_questions = new.get("questions", []) or []
        entries.extend(_question_entries(key, title, old_questions, new_questions))
    return entries


# ── Excel export ─────────────────────────────────────────────────────────────

_HEADER_FILL = "1F4E78"


def _write_table(ws, start_row, headers, rows):
    """Write a header + data table at ``start_row``; returns the next free row."""
    from openpyxl.styles import Font, PatternFill

    for column, name in enumerate(headers, start=1):
        cell = ws.cell(row=start_row, column=column, value=name)
        cell.font = Font(bold=True, color="FFFFFF")
        cell.fill = PatternFill("solid", fgColor=_HEADER_FILL)
    for offset, row in enumerate(rows, start=1):
        for column, value in enumerate(row, start=1):
            ws.cell(row=start_row + offset, column=column, value=value)
    return start_row + len(rows) + 1  # one blank row after the table


def _style_header_row(ws, row_number, total_columns):
    """Style an existing header row (white bold on dark blue)."""
    from openpyxl.styles import Font, PatternFill

    for column in range(1, total_columns + 1):
        cell = ws.cell(row=row_number, column=column)
        cell.font = Font(bold=True, color="FFFFFF")
        cell.fill = PatternFill("solid", fgColor=_HEADER_FILL)


def _autofit(ws, max_width=48):
    from openpyxl.utils import get_column_letter

    for column_cells in ws.columns:
        width = 0
        letter = get_column_letter(column_cells[0].column)
        for cell in column_cells:
            if cell.value is None:
                continue
            length = max(len(str(cell.value).split("\n")[0]), 8)
            width = max(width, length)
        ws.column_dimensions[letter].width = min(width + 2, max_width)


def write_report_xlsx(
    path,
    report,
    title="HealthAccess - Stakeholder Status Report",
    generated_at="",
    repository="",
    changelog=None,
):
    """Write the report structure to a styled .xlsx workbook.

    ``changelog`` is a dict with ``entries`` (from :func:`diff_reports`) and an
    optional ``baseline`` timestamp of the snapshot being compared against.
    """
    from openpyxl import Workbook
    from openpyxl.styles import Font

    wb = Workbook()

    # ── Overview sheet ──────────────────────────────────────────────────────
    ws = wb.active
    ws.title = "Overview"
    ws["A1"] = title
    ws["A1"].font = Font(bold=True, size=14)
    meta = f"Generated {generated_at}" + (f"  |  {repository}" if repository else "")
    ws["A2"] = meta

    def _section(ws, row, text):
        ws.cell(row=row, column=1, value=text).font = Font(bold=True, size=12)
        return row + 1

    cursor = _section(ws, 4, "Summary")
    summary = report["summary"]
    cursor = _write_table(
        ws,
        cursor,
        ["Metric", "Planned", "Open", "Closed", "Blocked", "Overdue", "Unassigned"],
        [
            [
                "Count",
                summary["planned"],
                summary["open"],
                summary["closed"],
                summary["blocked"],
                summary["overdue"],
                summary["unassigned"],
            ]
        ],
    )
    cursor += 1

    cursor = _section(ws, cursor, "Epics (by Gate)")
    gate_headers = [
        "Epic (Gate)",
        "Tasks",
        "Planned",
        "Open",
        "Closed",
        "Blocked",
        "Overdue",
        "Unassigned",
        "Next deadline",
    ]
    gate_rows = [
        [
            gate["name"],
            gate["tasks"],
            gate["planned"],
            gate["open"],
            gate["closed"],
            gate["blocked"],
            gate["overdue"],
            gate["unassigned"],
            gate["next_deadline"],
        ]
        for gate in report["gates"]
    ]
    cursor = _write_table(ws, cursor, gate_headers, gate_rows)
    cursor += 1

    cursor = _section(ws, cursor, "Streams (ownership)")
    stream_headers = [
        "Stream",
        "Tasks",
        "Planned",
        "Open",
        "Closed",
        "Blocked",
        "Overdue",
        "Next deadline",
    ]
    stream_rows = [
        [
            stream["name"],
            stream["tasks"],
            stream["planned"],
            stream["open"],
            stream["closed"],
            stream["blocked"],
            stream["overdue"],
            stream["next_deadline"],
        ]
        for stream in report["streams"]
    ]
    _write_table(ws, cursor, stream_headers, stream_rows)
    ws.freeze_panes = "A3"
    _autofit(ws)

    # ── Changelog sheet ─────────────────────────────────────────────────────
    changelog = changelog or {}
    entries = changelog.get("entries") or []
    baseline = changelog.get("baseline")
    ws = wb.create_sheet("Changelog")
    ws["A1"] = "Changelog - changes since the previous export"
    ws["A1"].font = Font(bold=True, size=14)
    if baseline:
        ws["A2"] = f"Compared against the snapshot of {baseline}"
    else:
        ws["A2"] = "No previous snapshot found - this export establishes the baseline"
    changelog_header = ["Sheet", "Task", "What changed", "Before", "After"]
    data_start = 4
    for column, name in enumerate(changelog_header, start=1):
        ws.cell(row=data_start, column=column, value=name)
    _style_header_row(ws, data_start, len(changelog_header))
    for offset, entry in enumerate(entries, start=1):
        row_number = data_start + offset
        ws.cell(row=row_number, column=1, value=entry["sheet"])
        ws.cell(row=row_number, column=2, value=entry["task"])
        ws.cell(row=row_number, column=3, value=entry["change"])
        ws.cell(row=row_number, column=4, value=entry["before"])
        ws.cell(row=row_number, column=5, value=entry["after"])
    if not entries and baseline:
        note = ws.cell(row=data_start + 1, column=1, value="No changes since the previous export.")
        note.font = Font(italic=True)
    ws.freeze_panes = "A2"
    if entries:
        ws.auto_filter.ref = ws.dimensions
    _autofit(ws)

    # ── Tasks sheet ─────────────────────────────────────────────────────────
    ws = wb.create_sheet("Tasks")
    task_header = [
        "Key",
        "Epic (Gate)",
        "Stream",
        "Title",
        "State",
        "Assignee",
        "Deadline",
        "Effort",
        "Blocked by",
        "Related",
        "GitHub",
        "Open questions",
    ]
    ws.append(task_header)
    _style_header_row(ws, 1, len(task_header))
    for row in report["rows"]:
        ws.append(
            [
                row["key"],
                row["gate"],
                row["stream"],
                row["title"],
                row["state"],
                row["assignee"],
                row["deadline"],
                row["effort"],
                row["blocked_by"],
                row["related"],
                row["github_url"] or "",
                len(row["questions"]),
            ]
        )
    ws.freeze_panes = "A2"
    ws.auto_filter.ref = ws.dimensions
    _autofit(ws)

    # ── Questions sheet ─────────────────────────────────────────────────────
    ws = wb.create_sheet("Questions")
    question_header = ["Epic (Gate)", "Task", "Question", "Resolved?"]
    ws.append(question_header)
    _style_header_row(ws, 1, len(question_header))
    for item in report["questions"]:
        ws.append(
            [
                item["gate"],
                f"{item['key']} {item['title']}",
                item["question"],
                "Yes" if item["resolved"] else "No",
            ]
        )
    ws.freeze_panes = "A2"
    ws.auto_filter.ref = ws.dimensions
    _autofit(ws)

    wb.save(path)
    return path
